### ISSUE TITLE
Delete button not working for knifeOnlyNumbers directive in matInput angular

### ISSUE THREAD

**Issue by navneetagrwl** [marcelocanales/ng-knife#1]
Delete button not working for knifeOnlyNumbers directive in matInput angular

**Comment by RaviTejaVattem** [comment]
Raised PR #2 for this issue.

**Comment by marcelocanales** [comment]
Fixed - v0.2.6 by RaviTejaVattem

**Comment by navneetagrwl** [comment]
Still this is not working I have observed this is deleted  e.keyCode === 46 which is the fix for this issue
