### ISSUE TITLE
Delete button not working for knifeOnlyNumbers directive in matInput angular

### ISSUE THREAD

**Issue by navneetagrwl** [marcelocanales/ng-knife#5]
still this is the issue #1

**Comment by navneetagrwl** [comment]
Still this is not working I have observed this is deleted e.keyCode === 46 which is the fix for this issue

**Comment by marcelocanales** [comment]
You are right, this is an error of version v0.2.7, it will be corrected as soon as possible. Thanks.

**Comment by marcelocanales** [comment]
Fixed. v0.2.8
